### DISCUSSION TITLE
[Feature] Configuration storage and abstraction for plugin

### DISCUSSION THREAD

**Discussion by namit-chandwani** [aerogear/charmil#100] [Ideas]
# Description
Each plugin can have its own configuration, and if there isn't a proper storage system in place, the host CLI may end up dealing with a large number of config files.

Our objective is to offer a suitable mechanism for plugins to compose configuration and export it to the Host CLI.

# Proposed Solution
Create a wrapper around [Viper](https://github.com/spf13/viper) and allow the plugins to define their local config using the wrapper functions that we'll provide. This config can then be merged into the config file of the Host CLI using the available set of functions.

### POC:
- **https://github.com/namit-chandwani/charmil-config-poc**

 ### End Result:
Here I've used a YAML file as an example, but JSON, TOML, etc. can also be used instead.
 - #### Initial Host CLI Config File:
	```yaml
	key1: "val1"
	key2: "val2"
	key3: "val3"
	```
 - #### Date Plugin Config Map:
	```go
	map[key4:value4 key5:value5 key6:value6]
	```
 - #### Echo Plugin Config Map:
	```go
	map[key7:value7 key8:value8 key9:value9]
	```
- #### Final Host CLI Config File after Merging:
	```yaml
	key1: "val1"
	key2: "val2"
	key3: "val3"

	plugins:
	  date:
	    key4: "val4"
	    key5: "val5"
	    key6: "val6"
	    
	  echo:
	    key7: "val7"
	    key8: "val8"
	    key9: "val9"
	```
# Alternative Solution (Used in RHOAS)
- Provide an interface with required method signatures to read/write from a config file.
- This interface is made available in the `Factory` struct and hence can be implemented in the Host CLI and then passed down to the plugins for managing their config.
